version: '3.4'

services:
  redis-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
    volumes:
        - /path/to/local/dаta:/root/redis
        - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
        - REDIS_PASSWORD=root
        - REDIS_PORT=6379
        - REDIS_DATABASES=16